---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alpine
  template:
    metadata:
      labels:
        app: alpine
    spec:
      containers:
      - name: alpine
        image: alpine:latest
        command: [ "/bin/sh", "-c", "sleep 3600" ]

---
apiVersion: v1
kind: Service
metadata:
  name: alpine-service
  annotations:
    lbipam.cilium.io/ips: "10.1.135.150" # Annotation for Cilium LoadBalancer IP
spec:
  type: LoadBalancer
  selector:
    app: alpine # Make sure this matches the label in your Deployment
  ports:
  - port: 80 # External port
    targetPort: 80 # Port on the pod (container level)
    protocol: TCP
