# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:C2GaTB2CjnmbCAwEC+3DzWE4nEfunVULxoORy2wajrP3x5aUKlXIPw==,iv:znlEEwhRfAVJYc8lII3rOJtxcoDJEiAMMFkoONfQmmE=,tag:/hQLWhef44a/uvUK92JntA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1nl0mkt927jk6yj9xk3w8u0ylmlcq25e3jxkhkqss7tq3dz2rrflq7e7jd9
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTOVlQNDBXMTgyNnB1bXIw
        RDBJaUplRmVUWW5tRm03OUxvWnlqakxlMWx3CjgzMkJzZHNrbmJFOExQcXBRT1RL
        RUEyTmJRQTk4R3JHRHV0UG9nSXFodk0KLS0tIGRTZmVqaDQyd0ZVU3A1VWd5RmZ1
        U3dCMERDMTlGOXlRMDJDVWNBQUt4dEUK54SLOmaVfvQ1NgPjOMPdGBCtSM5D9oLX
        muazsoh1cc06dkGwQRyBBOpPs/2LAiRf3BLoEuw2xsjIUAcjAAaepA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-04-04T17:16:16Z"
  mac: ENC[AES256_GCM,data:T33QWhD5ppdo7V5ByB9uBDdsp8qmGKHIgr0GAKBjojFi4pxfOG9WTRpp6wQoHwUcsV1TOqL/5wpkB386HyFdmpBJZuMJZ4SvAdmUkvyVY1L71jq0KGqq7AQhPuaAELedBl2HUxEDhq2+0GKK9fakyiqU79YeJRg0sh21pShVDGU=,iv:Nu94djcNafrsVobDspyVnKQ1OCmXQ/fpZpzucF68uBk=,tag:z3h+XACGOjZMXJ2OFWMRGw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
