---
originRequest:
  originServerName: "external.astrateam.net"

ingress:
  - hostname: "astrateam.net"
    service: &svc https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.astrateam.net"
    service: *svc
  - service: http_status:404
