---
originRequest:
  originServerName: "external.astrateam.net"

ingress:
  - hostname: "astrateam.net"
    service: &svc https://cilium-gateway-external.kube-system.svc.cluster.local
  - hostname: "*.astrateam.net"
    service: *svc
  - service: http_status:404
