---
originRequest:
  originServerName: "external.astrateam.net"

ingress:
  - hostname: "astrateam.net"
    service: &svc https://envoy-gateway-external.networking.svc.cluster.local
  - hostname: "*.astrateam.net"
    service: *svc
  - service: http_status:404
